<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:property name="laser_foot_radius" value="0.01"/>
    <xacro:property name="laser_foot_thickness" value="0.03"/>
     <xacro:property name="laser_radius" value="0.025"/>
    <xacro:property name="laser_thickness" value="0.02"/>

    <joint name="laser_joint" type="fixed">
        <parent link="chassis"/>
        <child link="laser_frame"/>
        <origin xyz="0 0 ${chassis_thickness + laser_foot_thickness}" rpy="0 0 0"/>
    </joint>

    <link name="laser_frame">
        <visual>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <visual>
            <origin xyz="0 0 ${-laser_thickness}"/>
            <geometry>
                <cylinder radius="${laser_foot_radius}" length="${laser_foot_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="${laser_thickness}" radius="${laser_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="laser_frame">
        <material>Gazebo/Black</material>

        <sensor name="laser" type="ray">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>false</visualize>
            <update_rate>20</update_rate>
            <always_on>1</always_on>
            <ray>
                <scan>
                    <horizontal>
                        <samples>180</samples>
                        <resolution>1</resolution>
                        <min_angle>-1.570796</min_angle>
                        <max_angle>1.570796</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>${chassis_radius * 1}</min>
                    <max>${chassis_radius * 10}</max>
                    <resolution>0.01</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <!-- Noise parameters based on published spec for Hokuyo laser
                        achieving "+-30mm" accuracy at range < 10m.  A mean of 0.0m and
                        stddev of 0.01m will put 99.7% of samples within 0.03m of the true
                        reading. -->
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
            </ray>
           <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
                 <ros>
                    <argument>~/out:=lidar_scan</argument>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>laser_frame</frame_name>
            </plugin>
        </sensor>
    </gazebo>
</robot>